### ISSUE TITLE
Please store pretrained model in Google Drive where we can easily access, not able to access via Baidu Netdisk

### ISSUE THREAD

**Issue by Akshay-Ijantkar** [ying09/TextFuseNet#1]
@ying09

**Comment by ying09** [comment]
Ok, I will upload our pretrained models to Google Driver as soon as possible.

**Comment by ying09** [comment]
> @ying09

Ok, I will upload our pretrained models to Google Driver as soon as possible.

**Comment by Akshay-Ijantkar** [comment]
@ying09 Yes please, please try to do it as early as possible, great work on paper, by the way!

**Comment by ying09** [comment]
> @ying09 Yes please, please try to do it as early as possible, great work on paper, by the way!

I have uploaded. 
https://drive.google.com/drive/folders/18Ll-3bAmi4CR2eGTuM-j6fkMrSAaBV4Z?usp=sharing

**Comment by Akshay-Ijantkar** [comment]
@ying09  Thank you! I also suggest please try to have installation steps to reproduce your results, especially requirements.txt, Thanks!

**Comment by Akshay-Ijantkar** [comment]
@ying09 
I have saved weights in out_dir_r101 folder and then ran
```bash
python3 demo/icdar2013_detection.py  
```

I am getting this error:

```
    raise KeyError("Non-existent config key: {}".format(full_key))
KeyError: 'Non-existent config key: MODEL.TEXTFUSENET_MUTIL_PATH_FUSE_ON'
```

Can you please help me with it?

**Comment by Real-YeJ** [comment]
@Akshay-Ijantkar  It seems that you didn't install the conda environment  and build our TextFuseNet-detectron2 correctly.

**Comment by Akshay-Ijantkar** [comment]
@ying09 
Steps which I followed for getting started with this:
```
!git clone https://github.com/ying09/TextFuseNet.git

! pip install torch==1.6.0+cu101 torchvision==0.7.0+cu101 -f https://download.pytorch.org/whl/torch_stable.html

!python -m pip install 'git+https://github.com/facebookresearch/detectron2.git'

!pip install PyYAML==5.3.1

! python TextFuseNet/demo/icdar2015_detection.py  --input img540.jpg
```


Do I need to build it
`python setup.py build`

then install it:
`python setup.py install`

Please let me know! Thanks!

**Comment by Real-YeJ** [comment]
@Akshay-Ijantkar  
first, you need to install the conda environment according to the installation of detectron2.  I suggest that you configure it completely according to our requirements, because different versions may lead to unknown influence on performance. and then, you can build the TextFuseNet-detectron2 by running ' python setup.py build develop '.

**Comment by ying09** [comment]
> @ying09
> Steps which I followed for getting started with this:
> 
> ```
> !git clone https://github.com/ying09/TextFuseNet.git
> 
> ! pip install torch==1.6.0+cu101 torchvision==0.7.0+cu101 -f https://download.pytorch.org/whl/torch_stable.html
> 
> !python -m pip install 'git+https://github.com/facebookresearch/detectron2.git'
> 
> !pip install PyYAML==5.3.1
> 
> ! python TextFuseNet/demo/icdar2015_detection.py  --input img540.jpg
> ```
> 
> Do I need to build it
> `python setup.py build`
> 
> then install it:
> `python setup.py install`
> 
> Please let me know! Thanks!

We will give the instructions of step-by-step installation as soon as possible.

**Comment by ying09** [comment]
> @ying09
> Steps which I followed for getting started with this:
> 
> ```
> !git clone https://github.com/ying09/TextFuseNet.git
> 
> ! pip install torch==1.6.0+cu101 torchvision==0.7.0+cu101 -f https://download.pytorch.org/whl/torch_stable.html
> 
> !python -m pip install 'git+https://github.com/facebookresearch/detectron2.git'
> 
> !pip install PyYAML==5.3.1
> 
> ! python TextFuseNet/demo/icdar2015_detection.py  --input img540.jpg
> ```
> 
> Do I need to build it
> `python setup.py build`
> 
> then install it:
> `python setup.py install`
> 
> Please let me know! Thanks!

@Akshay-Ijantkar Hi, we have uploaded the instruction of step-by-step installation. 
Please refer to https://github.com/ying09/TextFuseNet/blob/master/step-by-step%20installation.txt

**Comment by Akshay-Ijantkar** [comment]
@ying09 Thank you! Will try that
