### ISSUE TITLE
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

### ISSUE THREAD

**Issue by CheonJiEun** [ying09/TextFuseNet#10]
I followed the step-by-step installation.
An error occurred while executing this code.

> python setup.py build develop

I used gcc-4.9, python 3.6.8.
Is it a version problem?

help me plz..

![image](https://user-images.githubusercontent.com/53997172/95676835-12ccae00-0bfc-11eb-865c-a10dd7b035a8.png)

**Comment by Real-YeJ** [comment]
@CheonJiEun  hey, it seems that there are some problems about cuda. did you use cuda when building it？or if you want to rebuild it, please delete the file 'build' and 'detectron2.egg-info'  first.

**Comment by CheonJiEun** [comment]
oh! I resolved it! 

> # CUDA 10.1
> pip install torch==1.4.0 torchvision==0.5.0

I had used torch==1.5.0.
But issue is resolved by downgrading torch installation to version 1.4.0.

Thank you :) 👍

**Comment by stoneyang** [comment]
@CheonJiEun Maybe you should take a reference at [this issue](https://github.com/MhLiao/DB/issues/154).
