### ISSUE TITLE
关于mutil_path_fuse_module

### ISSUE THREAD

**Issue by ustczhouyu** [ying09/TextFuseNet#14]
作者你好，paper中的流程图中显示的是 detection 分支和mask 分支都有mutil_path_fuse_module，但是在代码中只有roi_heads.py中的_forward_mask函数调用了mutil_path_fuse_module，好像检测分支并没有调用，请问在最终的实现中检测分支是否使用了mutil_path_fuse_module。

**Comment by Real-YeJ** [comment]
@ustczhouyu  detectron2实现是第二个版本的代码，没有调用。
