### ISSUE TITLE
关于图3中的不同字符的特征相加的作用

### ISSUE THREAD

**Issue by ustczhouyu** [ying09/TextFuseNet#15]
作者你好，对于Fig 3中的字符级特征，文中说的是将每个字符对应的特征resize到14×14然后相加，但是它们对应的是不同字符的特征，比如说B的特征和A的特征相加，这样的作用是什么呢？ 
期待作者的回复，谢谢

**Comment by Ineedangoodidea** [comment]
@Real-YeJ  Hello, I am also confused about this, please help us understand the reason for this. Thank you

**Comment by ying09** [comment]
@ustczhouyu 这里你可以这样理解，CNN特征提取和融合能力很强，我们在实验时采用这种方式进行特征融合时所得到的效果最好。同时我们也采用了例如concat等其他方式进行特征融合，最终的performance均达不到现在的这种融合方式。

**Comment by Ineedangoodidea** [comment]
您好，请问可以提供Textfusenet以ResNet50作为backbone的模型吗？我想follow您的这个工作，但是由于显卡不够，预训练要非常就，恳请您把ResNet50的预训练模型提供给我们，真的感激不尽。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ying09/TextFuseNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2020年11月5日(星期四) 中午12:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ying09/TextFuseNet] 关于图3中的不同字符的特征相加的作用 (#15)





 
@ustczhouyu 这里你可以这样理解，CNN特征提取和融合能力很强，我们在实验时采用这种方式进行特征融合时所得到的效果最好。同时我们也采用了例如concat等其他方式进行特征融合，最终的performance均达不到现在的这种融合方式。
