### ISSUE TITLE
How to get the corresponding mask area of all the texts in roi_heads.py in the inference stage, not the probability

### ISSUE THREAD

**Issue by Ineedangoodidea** [ying09/TextFuseNet#16]
Hello, in the def _forward_mask() of roi_heads.py, only the mask probability of each roi is provided in the inference phase. How can I get the mask of each text instance in roi_heads.py in the inference phase (that is, get the coordinates of the contour of each mask)?  I have tried for a long time, but still can't get the mask area of each text instance. Please help me, thanks.

**Comment by Real-YeJ** [comment]
@Ineedangoodidea  hey, please see the function '**mask_rcnn_inference**' in **mask_head.py**, and use **cv2.findcontour** to get contour of object.

**Comment by Ineedangoodidea** [comment]
Hello, how do I know in roi_heads.py which text instances are cut off during the cutting operation, please help me, thank you.





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ying09/TextFuseNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2020年10月30日(星期五) 晚上9:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ying09/TextFuseNet] How to get the corresponding mask area of all the texts in roi_heads.py in the inference stage, not the probability (#16)





 
@Ineedangoodidea  hey, please see the function 'mask_rcnn_inference' in mask_head.py, and use cv2.findcontour to get contour of object.
