### ISSUE TITLE
installation error 

### ISSUE THREAD

**Issue by songyh10** [ying09/TextFuseNet#17]
When I follow exactly the step-by-step installation instructions, I got the error message like this when I run the demo code:

![image](https://user-images.githubusercontent.com/4233990/97936495-80b65200-1d30-11eb-9987-28e9be8aac8e.png)

However, when I used I different version of pytorch which is installed by `pip install torch==1.6.0+cu101 torchvision==0.7.0+cu101 -f https://download.pytorch.org/whl/torch_stable.html`, then when I run `python setup.py build develop`, there comes the error:
![image](https://user-images.githubusercontent.com/4233990/97936608-e4d91600-1d30-11eb-8bfc-f77a1c681c53.png)
I tried to exactly copy your environment and changed my cuda version from 10.2 to 10.1 and followed your step-by-step instructions, but it still doesn't work. Can you give a hint on what I need to do? Thanks! @Real-YeJ

**Comment by Real-YeJ** [comment]
@songyh10  hey, the first problem shows that your pytorch can't work with your cuda. You have to make sure that the versions of pytorch and cuda are adaptable. I suggest  that you use our installation steps because other versions may cause unknown errors.

**Comment by songyh10** [comment]
Thanks for your response! I updated the command `conda install pytorch=1.3.1 torchvision cudatoolkit=10.1` with `conda install pytorch=1.3.1 torchvision cudatoolkit=10.1 -c pytorch`, and it works well now.
