### ISSUE TITLE
detectron2: ImportError: cannot import name '_C'

### ISSUE THREAD

**Issue by vanchung1995** [ying09/TextFuseNet#2]
It raise import error when I tried to run demo file 
![Screenshot from 2020-09-28 11-07-09](https://user-images.githubusercontent.com/15941200/94389698-c5bbf700-017a-11eb-89aa-a671633749e3.png)

**Comment by Real-YeJ** [comment]
@ @vanchung1995   You didn't install the conda environment and build our TextFuseNet-detectron2 correctly, and we will upload a step-by-step installation as soon as possible. please pay attention to our update.

**Comment by vanchung1995** [comment]
Thanks a lot. But how can I install it on pip? Can you create guideline for pip install ?

**Comment by vanchung1995** [comment]
The reason is detection was not installed correctly. Do the follow link:
https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5#scrollTo=b-i4hmGYk1dL

**Comment by vanchung1995** [comment]
update torch==1.6 and torchvision==0.7
