### ISSUE TITLE
the meaning of each tag in json file

### ISSUE THREAD

**Issue by BachTuan1991** [ying09/TextFuseNet#23]
"annotations":[
    {
        "area":14902.5,
        "bbox":[
            817,
            431,
            164,
            162
        ],..
What is "area"? 
And bbox is [xmin, ymin, xmax, ymax].
pls help me for create custom train.json

**Comment by ying09** [comment]
@BachTuan1991 it is same with coco json file. Please refer to https://cocodataset.org/#format-data
