### ISSUE TITLE
Train on ICDAR 2013 dataset

### ISSUE THREAD

**Issue by animesh-007** [ying09/TextFuseNet#26]
Please provide any code snippets for registering icdar 2013 dataset for training.

**Comment by Real-YeJ** [comment]
@animesh-007 hey, in this implementation, you only need to register icdar2013(put your path of images and annotation) in **detectron2/data/datasets/builtin.py**.

**Comment by animesh-007** [comment]
Thank you for guiding. If possible, can you share the `train.json` file for icdar 2013 dataset? I tried to make one by following official documentation of the coco dataset format but I am unable to make it properly.

**Comment by Real-YeJ** [comment]
@animesh-007 please refer to the annotations example
