### ISSUE TITLE
RuntimeError: Not compiled with GPU support

### ISSUE THREAD

**Issue by dhirajsuvarna** [ying09/TextFuseNet#27]
Hi @ying09 ,

I followed the instructions in the `step-by-step installation.txt` and was able to go through with no issues. 

However, when I try to run the `demo\icdar2013_detection.py` along with the required options, I get an error `RuntimeError: Not compiled with GPU support`. 

Both the input options and the error is shown in the screenshot below - 

![image](https://user-images.githubusercontent.com/4989127/100071593-3cb2fa80-2e61-11eb-8d4d-771e6aefd637.png)

Let me know if you need any other information.

**Comment by Real-YeJ** [comment]
@dhirajsuvarna 
When you compile TextFuseNet(or detectron2), it's necessary to compile with cuda and make sure your cuda and pytorch match.

**Comment by dhirajsuvarna** [comment]
@Real-YeJ , 
I did some searching into this error and it seems that **CUDA_HOME** env variable is not set.

When you say compile with `cuda` do I need to do anything other than the steps mentioned in `step-by-step installation.txt`? 
Is any other separate installation of `cuda` is required? or do I need to pass any compile time parameters?

**Comment by Real-YeJ** [comment]
@dhirajsuvarna  don't need other additional steps，just make sure make sure your cuda version is match with pytorch version. more details  https://github.com/facebookresearch/detectron2/issues/55

**Comment by dhirajsuvarna** [comment]
Here are the versions of the the packages installed 

![image](https://user-images.githubusercontent.com/4989127/100104049-b19b2a00-2e8b-11eb-9496-6471ef45f278.png)

![image](https://user-images.githubusercontent.com/4989127/100104083-bbbd2880-2e8b-11eb-82ef-9fa078ad46c4.png)

I manually added **CUDA_HOME** into my env point it to the folder shown below 

![image](https://user-images.githubusercontent.com/4989127/100104223-e7d8a980-2e8b-11eb-8ef7-aa4a3f0eaffd.png)

sadly still facing the error. 

Do you think my **CUDA_HOME** is pointing to the correct location? or should it be pointing to one of the three folders inside?
![image](https://user-images.githubusercontent.com/4989127/100104547-574e9900-2e8c-11eb-853d-fd542f02aef1.png)

**Comment by Real-YeJ** [comment]
@dhirajsuvarna  check the version of your cuda, and I suggest that compile on linux instead of windows.
