### ISSUE TITLE
How to get the word result in the word-level instance instead of the possibility? 

### ISSUE THREAD

**Issue by YSUN-coder** [ying09/TextFuseNet#29]
Hi, how to get the word result in the word-level instance instead of the possibility? Furthermore, could you give me some advice if I need it perform better for the vertical- or even inverted-type text using new training dataset?
Looking forward to your help. Thanks.

**Comment by Real-YeJ** [comment]
@YSUN-coder. our detection demo will save the contour(a list of polygon points) of word-level results to txt file.
