### ISSUE TITLE
KeyError: 'Non-existent config key: MODEL.TEXTFUSENET_MUTIL_PATH_FUSE_ON'

### ISSUE THREAD

**Issue by vanchung1995** [ying09/TextFuseNet#3]
This error raise on when I run python demo/***_detection.py

![Screenshot from 2020-09-29 15-57-57](https://user-images.githubusercontent.com/15941200/94536482-e6fd1000-026c-11eb-9900-cddbdfdff75d.png)

This is config file:
![Screenshot from 2020-09-29 16-01-29](https://user-images.githubusercontent.com/15941200/94536876-10b63700-026d-11eb-9188-0ff1a16622a3.png)

**Comment by Real-YeJ** [comment]
@vanchung1995  did you build the TextFuseNet-detectron2 by running 'python setup.py build develop'

**Comment by Real-YeJ** [comment]
@vanchung1995  you can install and build it again according to our step-by-step installation.

**Comment by vanchung1995** [comment]
I built detectron2 successfully via the guide at `https://github.com/facebookresearch/detectron2/blob/master/INSTALL.md`.
I use pip instead of conda

**Comment by Real-YeJ** [comment]
@vanchung1995  our TextFuseNet is based on the early detectron2.  Maybe there are some differences with the latest installation.

**Comment by xxAna** [comment]
@vanchung1995 have you solve this problem?
