### ISSUE TITLE
Confusing IoA computation

### ISSUE THREAD

**Issue by gen-ko** [ying09/TextFuseNet#31]
https://github.com/ying09/TextFuseNet/blob/d4708a9de5ed1da13df12e699896718ce4993e0b/detectron2/modeling/roi_heads/mutil_path_fuse_module.py#L79

It seems this will always generate a `inter_percent` of all `1`, since `boxes1` and `boxes2` are the same. Is this the expected behavior of the model illustrated in the paper?

**Comment by Real-YeJ** [comment]
inter_area returns a tensor with a size of M*M, we find internal characters for each word-level text.
