### ISSUE TITLE
Do you have an annotation tool for custom data?

### ISSUE THREAD

**Issue by bbangbin2780** [ying09/TextFuseNet#33]
I need tool to annotate custom data

please, provide it 

thanks

**Comment by Real-YeJ** [comment]
about how to annotate custom data, please refer to #11

**Comment by bbangbin2780** [comment]
I see that, but I'm still wondering if i need to create json file manually.

I appreciate your answer, Thanks

**Comment by Real-YeJ** [comment]
yeah, you should convert your annotations to a json file(COCO format), including word-level and character-level annotations

**Comment by bbangbin2780** [comment]
Thank you very much, I appreciate that

Then learning data according to detectron2 manual, right?

**Comment by Real-YeJ** [comment]
train a pre-trained model on Synthtext with word-level and character-level annotations, and then use the model to generate weakly supervised annotations on your custom datasets. all of it is based on detectron2 framework.
