### ISSUE TITLE
代码现在是否只支持batch_size==1?

### ISSUE THREAD

**Issue by jtcjump** [ying09/TextFuseNet#34]
Mutil_Path_Fuse_Module：：forward
if self.training:
            proposal_boxes = proposals[0].proposal_boxes
            classes = proposals[0].gt_classes
        else:
            proposal_boxes = proposals[0].pred_boxes
            classes = proposals[0].pred_classes

        if len(proposal_boxes) == 0:
              return x

代码中只取了proposals[0]，batch_size >1时 text = x[char_pos[i]] 会报错

**Comment by Real-YeJ** [comment]
@jtcjump 是的，后续会更新。
