### ISSUE TITLE
Training using 8gb GPU and inferencing using cpu

### ISSUE THREAD

**Issue by seekingdeep** [ying09/TextFuseNet#35]
hi there,
- can textfusenet be trained using a single 8gb gpu?
- can the inferencing be on cpu-only?
- - How much ram memory is required for inferencing?

**Comment by Real-YeJ** [comment]
@seekingdeep  
1. yes, but you have to train with smaller image_size and set IMS_PER_BATCH=1.
2. inference with cpu only pls refer to https://github.com/facebookresearch/detectron2.
3. not clear, it depends on your model and image_size.
