### ISSUE TITLE
How i can build detectron2 with cuda 10.0 or cpu

### ISSUE THREAD

**Issue by tanphuc16797** [ying09/TextFuseNet#4]
I have some problems when i tried to run python demo/icdar2013_detection.py on pytorch 1.4 - cuda 10.0

- Step-by-step installation at  https://github.com/facebookresearch/detectron2/blob/master/INSTALL.md
![image](https://user-images.githubusercontent.com/54257990/94638198-a8666480-0303-11eb-8948-67bb91183129.png)

- Step-by-step installation at https://github.com/ying09/TextFuseNet/blob/master/step-by-step%20installation.txt
![image](https://user-images.githubusercontent.com/54257990/94638705-c6809480-0304-11eb-9086-2828f7b1ff1d.png)

**Comment by Real-YeJ** [comment]
@tanphuc16797   
 For the first problem, our TextFuseNet is based on the early detectron2, which needs cuda ==10.1 and pytorch >= 1.3, so I suggest that you install it according to our installation. if you want to use pytorch 1.4 and cuda 10.0, please make sure they are suitable. The reason of KeyError is that you didn't build TextFuseNet by running 'python setup.py build develop'. 

For the second problem, our implementation needs gpu. Maybe you can find how to building detectron2 with cpu in https://github.com/facebookresearch/detectron2
