### ISSUE TITLE
Cannot use pre-trained model without GPU ?

### ISSUE THREAD

**Issue by rbgt** [ying09/TextFuseNet#49]
Hi,
I'd like to try the TextFuseNet architecture without training on new data but only to assess the performance of the model, is it possible to do it without GPU ?
I've followed the step by step installation guide and placed the detection model in a created folder according to the python file but when running the demo, it needs to have a GPU.

Is there something missing here ?

**Comment by rbgt** [comment]
Alright just found out it's possible to run prediction on CPU by setting "cpu" instead of "cuda" at one line in the "detectron2/config/default.py" file : 

from : `_C.MODEL.DEVICE = "cuda"`
switch to : `_C.MODEL.DEVICE = "cpu"`

**Comment by chenf99** [comment]
@rbgt Hi, did you run prediction on CPU successfully? I have modified `_C.MODEL.DEVICE = "cuda"` to `_C.MODEL.DEVICE = "cpu"`，but it shows Segmentation fault (core dumped).
