### ISSUE TITLE
How to run textfusenet on rtx 30xx gpu with cuda 11.x?

### ISSUE THREAD

**Issue by mobassir94** [ying09/TextFuseNet#56]
i was not able to run this project on rtx 3090 gpu,during inference i get some error like "not compiled on gpu",something like this,any guideline on how to run this on updated cuda/gpu architectures? thank you in advance

**Comment by sssimpleboy** [comment]
Had you succeeded?
i have to run the project by 3090 now.
thank you.

**Comment by sssimpleboy** [comment]
I have to run the project on 3090 now.
Had you solved this problem?
Thank you.
When I ran commend "python setup.py build develop" in "step-by-step installation",I got the error :

error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by mobassir94** [comment]
@sssimpleboy we made this project working long ago,can't remember everything correctly. first of all you should not blindly follow this instruction : https://github.com/ying09/TextFuseNet/blob/master/step-by-step%20installation.txt 
for rtx 3090
ampere based gpus like rtx 3060,3070,3080,3090 they do not support pytorch 1.3.1 and cudatoolkit=10.1

instead you need to run something like this : 

`pip3 install torch==1.8.2+cu111 torchvision==0.9.2+cu111 torchaudio===0.8.2 -f https://download.pytorch.org/whl/lts/1.8/torch_lts.html` 

when done, you will have working version of pyorch installed for rtx 3090 that is good to go with detectron2

again at this point the detectron2  0.1       won't work anymore for you,,,you will have to install detectron2 0.4 for your new environment,,,when you have 0.4 installed at that point this textfusenet implementation won't work anymore for you :D 
now you will have to  integrate the corresponding code(roi_head.py, seg_head.py, multi_path_fusion.py) to your new detectron2.
once done,textfusenet will start working for you.

**Comment by sssimpleboy** [comment]
haha , Thank you . 
I ran it with torch==1.8.1.
I will try to use 0.4 instead. 
haha.

**Comment by JaeYoungKim1** [comment]
Hello,
I'm struggling to integrate (roi_heads.py, seg_head.py, mutil_path_fuse_module.py) like you did in this link :
[https://github.com/ying09/TextFuseNet/issues/59](https://github.com/ying09/TextFuseNet/issues/59
)
And I think my setting is almost same as yours except those codes.
Could you tell me how you integrated roi_head.py for detectron2 0.4?
Or It would be appreciated if you share it.
Thank you.

**Comment by mobassir94** [comment]
@JaeYoungKim1 we have stopped working on this long ago. For us current best text detection model is dbresnet50. but i would like to share our last known working textfusenet version that worked for bangla text detection, here is the project : https://drive.google.com/drive/folders/1vfYmmAc9uQYDdj-aqIZtSYVANy3VSlBb?usp=sharing
i can't remember the details about how to run this project and what are the changes we made back then,check carefully to find the changes and try to understand them on your own but this project worked for us,we modified a lot of things and then this updated textfusenet worked for us with detectron2 version 0.4. best of luck.

**Comment by sssimpleboy** [comment]
> Hello, I'm struggling to integrate (roi_heads.py, seg_head.py, mutil_path_fuse_module.py) like you did in this link : #59 And I think my setting is almost same as yours except those codes. Could you tell me how you integrated roi_head.py for detectron2 0.4? Or It would be appreciated if you share it. Thank you.

we had given up.. the model is too large.

**Comment by JaeYoungKim1** [comment]
Oh Thank you very much.
I'll try and check what has been modified.
I hope everything goes well.
