### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by tadam98** [ying09/TextFuseNet#6]
Hi I am getting the following runtime error:
```
(textfusenet) mickey@MICKEY-2080TI:/mnt/d/download/GitHub/Examples/2020-09-28 TextFuseNet/TextFuseNet-master$ python demo/icdar2015_detection.py --input one-frame.jpg 
Config './configs/ocr/icdar2015_101_FPN.yaml' has no VERSION. Assuming it to be compatible with latest v2.
Traceback (most recent call last):
  File "demo/icdar2015_detection.py", line 128, in <module>
    for i in glob.glob(test_images_path):
  File "/home/mickey/miniconda3/envs/textfusenet/lib/python3.7/glob.py", line 20, in glob
    return list(iglob(pathname, recursive=recursive))
  File "/home/mickey/miniconda3/envs/textfusenet/lib/python3.7/glob.py", line 40, in _iglob
    dirname, basename = os.path.split(pathname)
  File "/home/mickey/miniconda3/envs/textfusenet/lib/python3.7/posixpath.py", line 107, in split
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not list
```

Best,
Mickey

**Comment by Real-YeJ** [comment]
@tadam98  path error

**Comment by tadam98** [comment]
The problem is in the code. the --input  processed in row 112 of icdar2015_detection.py (and the others)
`test_images_path = args.input`
 sets test_images_path to a list. not a string. while glob.glob requires a string. and this is the reported error.
`for i in glob.glob(test_images_path):`
Changed so that i runs on test_images_path and then another for on the glob.glob of i.

Can you send me a sample command line that would take an image called 1.jpg from a ./images folder?

**Comment by ying09** [comment]
> The problem is in the code. the --input processed in row 112 of icdar2015_detection.py (and the others)
> `test_images_path = args.input`
> sets test_images_path to a list. not a string. while glob.glob requires a string. and this is the reported error.
> `for i in glob.glob(test_images_path):`
> Changed so that i runs on test_images_path and then another for on the glob.glob of i.
> 
> Can you send me a sample command line that would take an image called 1.jpg from a ./images folder?

@tadam98 Hi,  the argument of '--input' is the folder of test images. We have modified the default and help of '--input'.

**Comment by tadam98** [comment]
It does not solve the error because test_images_path is of type **list** and glob.glob does not support it. (regardless of whatever one places after the --input parameter)

`TypeError: expected str, bytes or os.PathLike object, not list`

**Comment by tson1997** [comment]
> It does not solve the error because test_images_path is of type **list** and glob.glob does not support it. (regardless of whatever one places after the --input parameter)
> 
> `TypeError: expected str, bytes or os.PathLike object, not list`

Yeah, I encountered this problem too. I simply put test_images_path = args.input[0], then the problem was solved

**Comment by tadam98** [comment]
that works too. I made another fix. All I was trying to say is that the code as it is does not work.

**Comment by ying09** [comment]
Hi all. The argument of '--input' should be set to "./input_images/*.jpg". We have modified the default of '--input'.
