### ISSUE TITLE
Model stability

### ISSUE THREAD

**Issue by bschembri-UoM** [ying09/TextFuseNet#63]
Hello,

Which of the models you provide is the most stable one, please?

Thank you

**Comment by JungChulKoo** [comment]
Hi,  as i tried every model this project provides, it depends on the datasets you want to use, to finetune the pretrained model.  ICDAR2013 has more rectangular-like areas than ICDAR2015, so ICDAR2013 pretrained model would be more proper to be used for document-like images, than ICDAR2015 pretrained model.

**Comment by ying09** [comment]
@JungChulKoo thanks!
