### ISSUE TITLE
为什么配置文件里有NUM_GROUPS=32和WIDTH_PER_GROUP=8？

### ISSUE THREAD

**Issue by czczup** [ying09/TextFuseNet#65]
你好，关于配置文件有一些困惑。
为什么配置文件的model里有NUM_GROUPS=32和WIDTH_PER_GROUP=8
使用了这两项配置不应该是ResNeXt-32x8d吗?

config的注释里也是这么写的：
```
# Number of groups to use; 1 ==> ResNet; > 1 ==> ResNeXt
_C.MODEL.RESNETS.NUM_GROUPS = 1
```

**Comment by Real-YeJ** [comment]
@czczup 你好，基于detectron2的实现使用的是ResNeXt-101，相比于ResNet-101在各个数据集实现了进一步的提升
