### ISSUE TITLE
Demo for large images with multiple text instances

### ISSUE THREAD

**Issue by tson1997** [ying09/TextFuseNet#7]
I observed that when doing a demo, the model takes much of the GPU memory, making it difficult to test for large image with multiple text instances (crashed usually due to memory limit). Are there anyway to go around this, i.e., resize the image and test it or something?

**Comment by Real-YeJ** [comment]
@tson1997 yeah，we test the images on a single scale, and our gpu is Tesla V100(16 G). you have to resize the image limited by GPU memory, which will lead bad influence to  the performance of model.
