### ISSUE TITLE
train the model on Icdar2015 dataset

### ISSUE THREAD

**Issue by tson1997** [ying09/TextFuseNet#8]
Good day! I want to train the model on ICDAR 2015 dataset. Are there anyway to convert the data in such form that the loader can understand? I already read the README file in datasets folder, but I am looking for some conversion code that helps. Thank you

**Comment by Real-YeJ** [comment]
@tson1997  hey, you should change the annotations of ICDAR2015 into COCO format(txt->json), and register your datasets. For more details that how to train your own custom datasets, please refer to https://github.com/facebookresearch/detectron2.

**Comment by animesh-007** [comment]
Hello @tson1997. If you were able to train your model on ICDAR 2015 dataset, can you provide any code snippets that you used for converting data and for registering?

**Comment by chenf99** [comment]
@animesh-007 Hello, did you train successfully? I also encountered this problem and I want to know how to get train.json and test.json for ICDAR2015.

**Comment by animesh-007** [comment]
> @animesh-007 Hello, did you train successfully? I also encountered this problem, and I want to know how to get train.json and test.json for ICDAR2015.

Yes, I was able to train the network successfully. You have to create train.json and test.json by yourself. As authors have not provided it yet as far, I remember.

**Comment by chenf99** [comment]
> > @animesh-007 Hello, did you train successfully? I also encountered this problem, and I want to know how to get train.json and test.json for ICDAR2015.
> 
> Yes, I was able to train the network successfully. You have to create train.json and test.json by yourself. As authors have not provided it yet as far, I remember.

Thanks  for the reply. I tried to create the json file by myself, but it seems that something get wrong. If possible, could you please provide the  code used for converting? Thanks a lot.

**Comment by animesh-007** [comment]
> > > @animesh-007 Hello, did you train successfully? I also encountered this problem, and I want to know how to get train.json and test.json for ICDAR2015.
> > 
> > 
> > Yes, I was able to train the network successfully. You have to create train.json and test.json by yourself. As authors have not provided it yet as far, I remember.
> 
> Thanks for the reply. I tried to create the json file by myself, but it seems that something get wrong. If possible, could you please provide the code used for converting? Thanks a lot.

Sure, Can you send me an email regarding this?

**Comment by chenf99** [comment]
@animesh-007 Thank you! I have send an email to animeshgupta.thapar@gmail.com yesterday but I didn't got a response. I'm not sure whether you received the email.

**Comment by BloomBerry** [comment]
Hi @chenf99 Can I also have your converting code as well?? My e-mail is jyjang1090@gmail. Thanks in advance!

**Comment by LIYHUI** [comment]
@chenf99 Hi, can you kindly share the converting code? My e-mail is lyhxjtu123@gmail.com.

**Comment by HassanBinHaroon** [comment]
@chenf99 Can you please share the code for creating train/val.json file (data registration). My email is hharoon.msee21seecs@seecs.edu.pk

**Comment by MinhHuuNguyen** [comment]
@chenf99 Hi, thanks for your hard-working, can you please share the code or the json file? My email is minh.nguyenhuu@pixta.co.jp
