### ISSUE TITLE
哪里有对应的json文件

### ISSUE THREAD

**Issue by ustczhouyu** [ying09/TextFuseNet#9]
作者你好！请问能提供对应的json文件吗？谢谢。

**Comment by Real-YeJ** [comment]
@ustczhouyu 我们会尽快上传一个json样例用于参考。

**Comment by ying09** [comment]
> 作者你好！请问能提供对应的json文件吗？谢谢。

Please refer to annotation_example.

**Comment by ustczhouyu** [comment]
Thank you very much.
